version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Example of specifying a runtime version
    commands:
      - echo Installing dependencies
      - cd jen-doc
      - npm install

  pre_build:
    commands:
      - echo Pre-build phase
      - echo Listing all folders in the repository
      - ls -al

  build:
    commands:
      - echo Build phase
      - echo Performing build operations
      # Add your build commands here
      - cd jen-doc
      - echo Listing all files in jen-doc directory
      - ls -al

  post_build:
    commands:
      - echo Post-build phase
      - echo Listing all folders again
      - ls -al
      # Any additional post-build commands

artifacts:
  files:
    - '**/*'
  discard-paths: no
